Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using Reciicer.Models.Entities;
using Reciicer.Repository.Interface;
using Reciicer.Service.Cliente;
using Reciicer.Service.Premiacao;

namespace Reciicer.Controllers
{
    
    public class ClienteController : Controller
    {

        
        private readonly ClienteService _clienteService;
        private readonly PremiacaoService _premiacaoService;
        private readonly IEmailService _emailService;
        

        public ClienteController(ClienteService clienteService, IEmailService emailService, PremiacaoService premiacaoService)
        {
            
            _clienteService = clienteService;
            _premiacaoService = premiacaoService;
            _emailService = emailService;
            
        }

        public IActionResult Index()
        {
            return View(_clienteService.ListarCliente(Convert.ToInt32(User.FindFirst("PontoColetaId")?.Value)));
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // evitar crsf
        public IActionResult Create(Cliente cliente)
        {
           
            _clienteService.RegistrarCliente(cliente);

            return RedirectToAction("Index");
         }

        [HttpGet]
        public IActionResult Read(int id)
        { 
                        
            return View(_clienteService.ObterClientePorId(id));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var cliente = _clienteService.ObterClientePorId(id);

            return View(cliente);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // evitar crsf
        public IActionResult Update(Cliente cliente)
        {
            _clienteService.AtualizarCliente(cliente);

            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            _clienteService.ExcluirCliente(id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ClientePremiacao(int? premiacaoId )
        {     
            return View(_premiacaoService.MontarViewModelPremiarCliente(premiacaoId));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult NotificarClientePremiacao(string email, int premiacaoId)
        { 
            
            var emailEnviado =  _emailService.EnviarEmail("guhstudante@gmail.com", "Premiação Disponível",_emailService.MontarEmailBody());

            if(emailEnviado)
            {
               TempData["Mensagem"] = $"Email para {email} enviado!";
            }
            else
            {
                TempData["Mensagem"] = $"Falha ao enviar o email para {email}.";
            }

            return RedirectToAction("ClientePremiacao", new {premiacaoId});
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/ColetaController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Reciicer.Models.ColetaViewModels;
using Reciicer.Models.Entities;
using Reciicer.Service.Coleta;
using Reciicer.Service.Estoque;
using Reciicer.Service.Material;
using Reciicer.Service.Material_Coleta;



namespace Reciicer.Controllers
{
    
    public class ColetaController : Controller
    {
        private readonly ColetaService _coletaService;
        private readonly MaterialService _materialService;
        private readonly Material_ColetaService _material_ColetaService;
        private readonly EstoqueService _estoqueService;
        private readonly UserManager<UsuarioIdentity> _userManager;

        public ColetaController(ColetaService coletaService, MaterialService materialService, Material_ColetaService  material_ColetaService, 
        EstoqueService estoqueService, UserManager<UsuarioIdentity> userManager)   
        {
            _coletaService = coletaService;
            _materialService = materialService;
            _material_ColetaService = material_ColetaService;
            _estoqueService = estoqueService;
            _userManager = userManager;

        }


        public IActionResult Index()
        { 
            var pontoColetaId = Convert.ToInt32(User.FindFirst("PontoColetaId")!.Value);
            
            return View(_coletaService.ListarColeta(pontoColetaId));
        }

        [HttpGet]
        public IActionResult Create()
        {
            var pontoColetaId = Convert.ToInt32(User.FindFirst("PontoColetaId")!.Value);

            var coletaCreate = _coletaService.ObterColetaCreateViewModel(pontoColetaId);

            return View(coletaCreate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AdicionarColetaCliente(ColetaCreateViewModel coletaCreateViewModel)
        {       
            //Cria a Coleta para o cliente
            _coletaService.EfetuarColetaCliente(coletaCreateViewModel, User);

            var coletaCreateViewCliente =_coletaService.ObterColetaCreateViewModelComUltimaColeta(coletaCreateViewModel.ClienteId, Convert.ToInt32(User.FindFirst("PontoColetaId")!.Value));
    
            return View("Create", coletaCreateViewCliente);
            
        }

        //Carregar drop Material de acordo com o Tipo Material selecionado
        // dinamicamente na view Coleta/Create
        [HttpGet]
        public JsonResult ObterMaterialByTipoMaterialId(int tipoMaterialId)
        {
            return Json(_materialService.PopularSelectFiltrandoPorTipoMaterialId(tipoMaterialId));
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AdicionarColetaTabela(ColetaCreateViewModel coletaCreateViewModel)
        {
                var usuarioLogado = await _userManager.GetUserAsync(User); 
            
                var materialColeta =  new Material_Coleta{
                    Peso = coletaCreateViewModel.Peso,
                    Quantidade = coletaCreateViewModel.Quantidade,
                    ColetaId = coletaCreateViewModel.ColetaId,
                    MaterialId = coletaCreateViewModel.MaterialId
                };

                var viewModel = _coletaService.ObterColetaCreateViewModelComMaterialColeta(coletaCreateViewModel.ClienteId, materialColeta);

                _estoqueService.AdicionarMaterialEstoque(materialColeta, usuarioLogado!.PontoColetaId);

                return View("Create", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletarMaterialColeta(int id, int clienteId)
        {
            _material_ColetaService.ExcluirMaterialColeta(id);

            var coletaCreateViewModel = _coletaService.ObterColetaCreateViewModelComMaterialColeta(clienteId);
            
            return View("Create", coletaCreateViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CalcularPontuacaoColeta(int coletaId)
        {               
            _coletaService.CalcularPontuacaoColeta(coletaId);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Read(int id)
        { 
            return View(_coletaService.ObterColetaReadViewModel(id));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(_coletaService.ObterUpdateViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AtualizarColetaTabela(ColetaUpdateViewModel viewModel)
        {
            var usuarioLogado = await _userManager.GetUserAsync(User); 

            var materialColeta = new Material_Coleta
            {
                ColetaId = viewModel.ColetaId,
                MaterialId = viewModel.MaterialId,
                Peso = viewModel.Peso,
                Quantidade = viewModel.Quantidade
            };

            _material_ColetaService.RegistrarMaterialColeta(materialColeta);

            _estoqueService.AdicionarMaterialEstoque(materialColeta, usuarioLogado!.PontoColetaId);

            var viewModelUpdate = _coletaService.ObterUpdateViewModel(viewModel.ColetaId);

            return View("Update", viewModelUpdate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemoverMaterialColetaTabelaViewUpdate(int id, int coletaId)
        {

            _estoqueService.RemoverMaterialEstoque(id);
            
            _material_ColetaService.ExcluirMaterialColeta(id);

            var viewModel = _coletaService.ObterUpdateViewModel(coletaId);

            return View("Update", viewModel);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {

            _estoqueService.ExcluirMateriaisEstoquePorColetaId(id);
            
            _coletaService.ExcluirColeta(id);

            return RedirectToAction("Index");
        }

    }
}

Controllers/EstoqueController.cs
using Microsoft.AspNetCore.Mvc;
using Reciicer.Models.Entities;
using Reciicer.Models.EstoqueViewModels;
using Reciicer.Service.Estoque;
using Reciicer.Service.EstoqueMaterial;
using Reciicer.Service.PontoColeta;


namespace Reciicer.Controllers
{
    
    public class EstoqueController : Controller
    {
        
        private readonly EstoqueService _estoqueService;
        private readonly PontoColetaService _pontoColetaService;
        private readonly EstoqueMaterialService _estoqueMaterialService;

        public EstoqueController(EstoqueService estoqueService, PontoColetaService pontoColetaService, EstoqueMaterialService estoqueMaterialService)
        {
            _estoqueService = estoqueService;
            _pontoColetaService = pontoColetaService;
            _estoqueMaterialService = estoqueMaterialService;
        }

        public IActionResult Index()
        {
            return View(_estoqueService.ListarEstoque());
        }

        [HttpGet]
        public IActionResult Create()
        {
            var estoqueCreateViewModel = new EstoqueCreateViewModel
            {
                PontoColetas = _pontoColetaService.ListarPontoColeta()
            };

            return View(estoqueCreateViewModel);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Estoque estoque)
        {   
            _estoqueService.RegistrarEstoque(estoque);
            
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Read(int id)
        { 
            var model = new EstoqueReadViewModel(){
                Estoque = _estoqueService.ObterEstoquePorId(id),
                EstoqueMateriais = _estoqueMaterialService.ObterEstoqueMaterialPorEstoqueId(id).Where(em => em.Quantidade != 0 || em.Peso != 0)
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var model  =  new EstoqueCreateViewModel(){
                Estoque = _estoqueService.ObterEstoquePorId(id),
                PontoColetas = _pontoColetaService.ListarPontoColeta()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Estoque estoque)
        {
            _estoqueService.AtualizarEstoque(estoque);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        { 
             _estoqueService.ExcluirEstoque(id);

            return RedirectToAction("Index");
        }


    }
}

Controllers/RoleController.cs
using Reciicer.Models.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Reciicer.Models.RoleViewModels;
using Reciicer.Service.PontoColeta;
using System.Security.Claims;
namespace Reciicer.Controllers
{

    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly UserManager<UsuarioIdentity> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly PontoColetaService _pontoColetaService;
        

        public RoleController(UserManager<UsuarioIdentity> userManager, PontoColetaService pontoColetaService, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _pontoColetaService = pontoColetaService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var users = _userManager.Users.ToList().Where(u => u.PontoColetaId == Convert.ToInt32(User.FindFirst("PontoColetaId")?.Value)).ToList();
            var model = new UserRoleListViewModel
            {
                Users = new List<UserRoleViewModel>()
            };

            foreach (var user in users)
            {
                var roles = await _userManager.GetRolesAsync(user);

                
                model.Users.Add(new UserRoleViewModel
                {
                    Id = user.Id,
                    UserName = user.NormalizedUserName!,
                    PontoColeta = _pontoColetaService.ObterPontoColetaPorId(user.PontoColetaId).Nome,
                    Email = user.Email,
                    Roles = roles.ToList()
                });
            }
            
            
            return View(model);
        }

        [HttpGet]
        public IActionResult Read(string id)
        { 
            var user = _userManager.Users.FirstOrDefault(u => u.Id == id);
            
            var model = new UserRoleViewModel
            {
                Id = user!.Id,
                UserName = user.NormalizedUserName!,
                PontoColeta = _pontoColetaService.ObterPontoColetaPorId(user.PontoColetaId).Nome ?? string.Empty,
                Email = user!.Email ?? string.Empty,
                Role = _userManager.GetRolesAsync(user).Result.FirstOrDefault() ?? string.Empty,
            };

            return View(model);
        }

        [HttpGet]
        public IActionResult Update(string id)
        { 
            var user = _userManager.Users.FirstOrDefault(u => u.Id == id);

            var userRole = _userManager.GetRolesAsync(user!).Result.FirstOrDefault() ?? string.Empty;

            
            var model = new UserRoleViewModel
            {
                Id = user!.Id,
                UserName = user.UserName!,
                PontoColetaId = _pontoColetaService.ObterPontoColetaPorId(user.PontoColetaId).Id,
                Email = user!.Email ?? string.Empty,
                RoleId = _roleManager.FindByNameAsync(userRole).Result!.Id,
                RolesList = _roleManager.Roles.ToList(),
                PontoColetas = _pontoColetaService.ListarPontoColeta(),
            };


            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UserRoleViewModel userRoleViewModel)
        { 
            var usuarioAtualizar =  _userManager.FindByIdAsync(userRoleViewModel.Id!).Result;

            usuarioAtualizar!.UserName = userRoleViewModel.UserName;
            usuarioAtualizar.Email = userRoleViewModel.Email;
            usuarioAtualizar.PontoColetaId = userRoleViewModel.PontoColetaId;
            
            await _userManager.UpdateAsync(usuarioAtualizar);
            await _userManager.RemoveFromRolesAsync(usuarioAtualizar, _userManager.GetRolesAsync(usuarioAtualizar).Result);
            await _userManager.AddToRoleAsync(usuarioAtualizar,  _roleManager.FindByIdAsync(userRoleViewModel.RoleId!).Result!.NormalizedName!);

            var currentClaims = await _userManager.GetClaimsAsync(usuarioAtualizar);
            var pontoColetaClaim = currentClaims.FirstOrDefault(c => c.Type == "PontoColetaId");
            var roleName = currentClaims.FirstOrDefault(c => c.Type == ClaimTypes.Role);

            await _userManager.ReplaceClaimAsync(usuarioAtualizar, pontoColetaClaim!, new Claim("PontoColetaId", userRoleViewModel.PontoColetaId.ToString()));
            await _userManager.ReplaceClaimAsync(usuarioAtualizar, roleName!, new Claim(ClaimTypes.Role, _roleManager.FindByIdAsync(userRoleViewModel.RoleId!).Result!.Name!));

            

            if(User.FindFirst(ClaimTypes.NameIdentifier)?.Value == usuarioAtualizar.Id)
            {
                TempData["Update"] = "Usuário atualizado com sucesso!";
                return RedirectToAction("Logout", "Login"); 
            }
            else    
                return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        { 
            
            var usuarioDeletar = await _userManager.FindByIdAsync(id);

            await _userManager.DeleteAsync(usuarioDeletar!);

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_AlertPartial.cshtml
@model (string mensagem, string alertType, string icon)

@if (!string.IsNullOrEmpty(Model.mensagem))
{
    <div class="alert alert-@Model.alertType" id="alert" role="alert">
         <i class="fa-solid fa-@Model.icon"></i> @Model.mensagem
    </div>
}

Views/Shared/_HeaderMobilePartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Reciicer.Models.Entities
@inject UserManager<UsuarioIdentity> _userManager

@{
    var userIdentity =  _userManager.GetUserAsync(User).Result;
    var roles = _userManager.GetRolesAsync(userIdentity!).Result;

    var isAdmin = roles.Contains("Admin");
}

<!-- HEADER MOBILE-->
<header class="header-mobile d-block d-lg-none">
    <div class="header-mobile__bar">
        <div class="container-fluid">
            <div class="header-mobile-inner">
                <a asp-action="Index" asp-controller="Home">
                    <img src="~/img/login.png" alt="Reciicer" width="150" height="50"/>
                </a>
                <button class="hamburger hamburger--slider" type="button">
                    <span class="hamburger-box">
                        <span class="hamburger-inner"></span>
                    </span>
                </button>
            </div>
        </div>
    </div>
    <nav class="navbar-mobile">
        <div class="container-fluid">
            <ul class="navbar-mobile__list list-unstyled">
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-person"></i>Cliente</a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a asp-controller="Cliente" asp-action="Index"><i class="fa-solid fa-list"></i>Listar</a>
                        </li>
                        <li>
                            <a asp-controller="Cliente" asp-action="ClientePremiacao"><i class="fa-solid fa-envelope"></i>Notificar</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="Coleta" asp-action="Index">
                        <i class="fa-solid fa-recycle "></i>Coleta</a>
                </li>
                @if(isAdmin){
                <li>
                    <a asp-controller="PontoColeta" asp-action="Index">
                        <i class="fa-solid fa-location-dot"></i>Pontos de Coleta</a>
                </li>
                }
                <li>
                    <a asp-controller="Endereco" asp-action="Index">
                        <i class="fa-solid fa-map-pin"></i>Endereço</a>
                </li>
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-trophy"></i>Premiação</a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a asp-controller="Premiacao" asp-action="Index"><i class="fa-solid fa-list"></i>Listar</a>
                        </li>
                        <li>
                            <a asp-controller="Premiacao" asp-action="PremiacaoCliente"><i class="fa-solid fa-gift"></i>Premiar</a>
                        </li>
                    </ul>
                </li>
                @if(isAdmin){
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-file"></i>Relatórios</a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a asp-controller="Relatorio" asp-action="RelatorioPontuacao"><i class="fa-solid fa-ranking-star"></i>Pontuação</a>
                        </li>
                        <li>
                            <a asp-controller="Relatorio" asp-action="RelatorioRecolhimento"><i class="fa-solid fa-weight-hanging"></i>Recolhimento</a>
                        </li>
                    </ul>
                </li>
                }
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-tag"></i>Gestão Materiais</a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                        <li>
                            <a asp-controller="Material" asp-action="Index"><i class="fa-solid fa-tag"></i>Material</a>
                        </li>
                        <li>
                            <a asp-controller="TipoMaterial" asp-action="Index"><i class="fa-solid fa-gifts"></i>Tipo</a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-truck"></i>Gestão Recolhimento</a>
                    <ul class="navbar-mobile-sub__list list-unstyled js-sub-list">
                 <li>
                    <a asp-controller="Cooperativa" asp-action="Index"> <i class="fa-solid fa-tree-city"></i>Cooperativa</a>
                </li>
                <li>
                    <a asp-controller="Recolhimento" asp-action="Index"><i class="fa-solid fa-truck-pickup"></i>Recolhimento</a>
                </li>
                <li>
                    <a asp-controller="Estoque" asp-action="Index"><i class="fa-solid fa-warehouse"></i>Estoque</a>
                </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!-- END HEADER MOBILE-->

Views/Shared/_MenuSideBarPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Reciicer.Models.Entities
@inject UserManager<UsuarioIdentity> _userManager

@{
    var userIdentity =  _userManager.GetUserAsync(User).Result;
    var roles = _userManager.GetRolesAsync(userIdentity!).Result;

    var isAdmin = roles.Contains("Admin");
}
        
<!-- MENU SIDEBAR-->
<aside class="menu-sidebar d-none d-lg-block">
    <div class="logo" style="overflow: hidden;">
        <a asp-action="Index" asp-controller="Home">
            <img src="~/img/logo.png" alt="Reciicer - ADM" />
        </a>
    </div>
    <div class="menu-sidebar__content js-scrollbar1">
        <nav class="navbar-sidebar">
            <ul class="list-unstyled navbar__list">
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-person"></i>Cliente</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a asp-controller="Cliente" asp-action="Index"><i class="fa-solid fa-list"></i>Listar</a>
                        </li>
                        <li>
                            <a asp-controller="Cliente" asp-action="ClientePremiacao"><i class="fa-solid fa-envelope"></i>Notificar</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="Coleta" asp-action="Index">
                        <i class="fa-solid fa-recycle "></i>Coleta</a>
                </li>
                @if(isAdmin){
                <li>
                    <a asp-controller="PontoColeta" asp-action="Index">
                        <i class="fa-solid fa-location-dot"></i>Pontos de Coleta</a>
                </li>
                }
                <li>
                    <a asp-controller="Endereco" asp-action="Index">
                        <i class="fa-solid fa-map-pin"></i>Endereço</a>
                </li>
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-trophy"></i>Premiação</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a asp-controller="Premiacao" asp-action="Index"><i class="fa-solid fa-list"></i>Listar</a>
                        </li>
                        <li>
                            <a asp-controller="Premiacao" asp-action="PremiacaoCliente"><i class="fa-solid fa-gift"></i>Premiar</a>
                        </li>
                    </ul>
                </li>
                @if(isAdmin){
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-file"></i>Relatórios</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a asp-controller="Relatorio" asp-action="RelatorioPontuacao"><i class="fa-solid fa-ranking-star"></i>Pontuação</a>
                        </li>
                        <li>
                            <a asp-controller="Relatorio" asp-action="RelatorioRecolhimento"><i class="fa-solid fa-weight-hanging"></i>Recolhimento</a>
                        </li>
                    </ul>
                </li>
                }
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-tag"></i>Gestão Materiais</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                        <li>
                            <a asp-controller="Material" asp-action="Index"><i class="fa-solid fa-tag"></i>Material</a>
                        </li>
                        <li>
                            <a asp-controller="TipoMaterial" asp-action="Index"><i class="fa-solid fa-gifts"></i>Tipo</a>
                        </li>
                    </ul>
                </li>
                <li class="has-sub">
                    <a class="js-arrow">
                        <i class="fa-solid fa-truck"></i>Gestão Recolhimento</a>
                    <ul class="list-unstyled navbar__sub-list js-sub-list">
                 <li>
                    <a asp-controller="Cooperativa" asp-action="Index"> <i class="fa-solid fa-tree-city"></i>Cooperativa</a>
                </li>
                <li>
                    <a asp-controller="Recolhimento" asp-action="Index"><i class="fa-solid fa-truck-pickup"></i>Recolhimento</a>
                </li>
                <li>
                    <a asp-controller="Estoque" asp-action="Index"><i class="fa-solid fa-warehouse"></i>Estoque</a>
                </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</aside>
<!-- END MENU SIDEBAR-->

Views/Shared/_NavPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using Reciicer.Models.Entities
@inject SignInManager<UsuarioIdentity> signInManager


@if(signInManager.IsSignedIn(User))
{
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa-solid fa-house pe-1"></i> Início</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index"><i class="fa-solid fa-person pe-1"></i> Cliente </a>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="fa-solid fa-person pe-1"></i> Cliente
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" asp-area="" asp-action="Create" asp-controller="Cliente"><i class="fa-solid fa-person-circle-plus"></i> Adicionar </a></li>
            <li><a class="dropdown-item" asp-area="" asp-action="InformarClientePremiacaoFiltro" asp-controller="Cliente" ><i class="fa-solid fa-tag pe-1"></i> Prêmios</a></li>
        </ul>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="PontoColeta" asp-action="Index"><i class="fa-solid fa-location-dot"></i> Pontos de Coleta </a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Coleta" asp-action="Index"><i class="fa-solid fa-recycle pe-1"></i> Coleta</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Premiacao" asp-action="Index"><i class="fa-solid fa-ranking-star pe-1"></i> Premiação</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Endereco" asp-action="Index"><i class="fa-solid fa-map-pin"></i> Endereço</a>
    </li>
 
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <i class="fa-solid fa-tag pe-1"></i> Gestão Materiais
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="Material" ><i class="fa-solid fa-tag pe-1"></i>Material </a></li>
            <li><a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="TipoMaterial" ><i class="fa-solid fa-gifts pe-1"></i>Tipo </a></li>
            <li><a class="dropdown-item" asp-area="" asp-action="Index" asp-controller="PontuacaoMaterial" ><i class="fa-solid fa-star pe-1"></i>Pontuação </a></li>
        </ul>
     </li>

}